### ISSUE TITLE
Soul cruza la linea de cielo o infierno y sigue de largo

### ISSUE THREAD

**Issue by latamakuchi** [latamakuchi/TheAfterLifeSucks#3]
Integrar como feature que represente una situación en la que nadie gana o resolver si lo tomamos como bug.

**Comment by latamakuchi** [comment]
Resuelto el bug (identificado el caso en el que pasa), pero falta decidir qué hacer en esa situación: pierden ambos o hacer que el soul quede clavado en el márgen/vuelva al centro/whatever.

**Comment by ithilethiel** [comment]
Se la come un shark volador (?)
